name: Tests on Chrome
on: push
jobs:
  chrome:
    runs-on: ubuntu-24.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6.1.0
        with:
          working-directory: ./cypress/e2e
      - run: npm install
      - run: npm test
