name: Cypress Tests

on:
  push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Instale as dependências NPM, faça o cache corretamente
      # e execute todos os testes do Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./e2e
          run: |
            npm install
            npm run cy:run 
